name: Chocolatey package update

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Authenticate to Chocolatey
        shell: powershell
        run: choco apikey --key ${{secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/
      
      - name: Update packages
        shell: powershell
        run: |
          Install-Module -Force Chocolatey-AU
          $Env:gist_id="${{secrets.GIST_ID}}"
          $Env:github_api_key="${{secrets.MYGITHUB_API_KEY}}"
          $Env:au_Push=$True
          .\update_all.ps1 -Verbose
          $info